### ISSUE TITLE
Dust threshold is 1 since bsv 1.0.11

### ISSUE THREAD

**Issue by libitx** [runonbitcoin/nimble#15]
This function is redundant:

https://github.com/runonbitcoin/nimble/blob/main/functions/calculate-dust.js

This is the relevant code in bitcoin-sv:

https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/primitives/transaction.h#L189-L195

**Comment by brentongunning** [comment]
Fixed in https://github.com/runonbitcoin/nimble/commit/255e81647da881f5b0afc9bc561d69466a7afc9b
